const fs = require('fs');
const path = require('path');

const newQuestions = [
  // TÜRKÇE (ÖNLİSANS - 15 questions)
  { id: "onl_tr_1", subject: "Türkçe", question: "Aşağıdakilerden hangisi bir yazım yanlışı içermektedir?", options: ["Bugün de gelmedi.", "Hiç kimse onu anlamadı.", "Herşey çok güzel olacak.", "Biraz daha sabretmelisin."], correctIndex: 2, difficulty: "easy", examType: "kpss_onlisans", explanation: "'Her şey' ayrı yazılmalıdır." },
  { id: "onl_tr_2", subject: "Türkçe", question: "Aşağıdaki cümlelerin hangisinde anlatım bozukluğu vardır?", options: ["Sınıftaki öğrencilerin çoğu başarılı oldu.", "Ben ve Ali yarın sinemaya gidecek.", "Bu konu hakkında hiçbir fikrim yok.", "Kitabı okuyup özetini çıkardı."], correctIndex: 1, difficulty: "medium", examType: "kpss_onlisans", explanation: "'Ben ve Ali' öznesi birinci çoğul şahıs (biz) kabul edildiği için yüklem 'gideceğiz' olmalıdır." },
  { id: "onl_tr_3", subject: "Türkçe", question: "'Gözden düşmek' deyiminin anlamı nedir?", options: ["Çok beğenilmek", "Değerini ve saygınlığını yitirmek", "Çok sevinmek", "Gözü bozulmak"], correctIndex: 1, difficulty: "easy", examType: "kpss_onlisans", explanation: "Gözden düşmek, bir kişinin eski değerini, saygınlığını veya güvenini yitirmesi anlamındadır." },
  { id: "onl_tr_4", subject: "Türkçe", question: "Hangi seçenekte ünsüz yumuşaması kuralına uyulmamıştır?", options: ["Ağacın", "Kitabı", "Hukuku", "Çocuğun"], correctIndex: 2, difficulty: "hard", examType: "kpss_onlisans", explanation: "'Hukuk' kelimesi Arapça kökenli olduğu için ünlüyle başlayan ek aldığında yumuşamaya uğramaz (hukuku)." },
  { id: "onl_tr_5", subject: "Türkçe", question: "Aşağıdaki altı çizili sözcüklerden hangisi yapısına göre türemiştir?", options: ["Evden", "Kitaplık", "Yolcuya", "Gözüm"], correctIndex: 1, difficulty: "medium", examType: "kpss_onlisans", explanation: "'Kitaplık' kelimesi, 'kitap' köküne '-lık' yapım eki getirilerek türetilmiştir." },
  { id: "onl_tr_6", subject: "Türkçe", question: "'İnce' kelimesi aşağıdakilerin hangisinde mecaz anlamda kullanılmıştır?", options: ["İnce bir kazak giymişti.", "Çok ince bir davranıştı.", "İncecik bir dal parçasıydı.", "Defterin yaprakları çok inceydi."], correctIndex: 1, difficulty: "easy", examType: "kpss_onlisans", explanation: "'İnce davranış' ifadesindeki 'ince', kalın karşıtı değil, 'nazik, düşünceli' anlamında mecazdır." },
  { id: "onl_tr_7", subject: "Türkçe", question: "Aşağıdaki cümlelerin hangisinde 'ki'nin yazımı yanlıştır?", options: ["Duvardaki tablo çok güzel.", "Anladım ki bu iş olmayacak.", "Evde ki hesap çarşıya uymadı.", "Sen ki benim en yakın arkadaşımsın."], correctIndex: 2, difficulty: "medium", examType: "kpss_onlisans", explanation: "'Evdeki hesap' şeklinde bitişik yazılmalıdır, çünkü burada sıfat yapan -ki ekidir." },
  { id: "onl_tr_8", subject: "Türkçe", question: "Hangisi sesteş (eş sesli) bir kelime değildir?", options: ["Yüz", "Gül", "Yol", "Masa"], correctIndex: 3, difficulty: "easy", examType: "kpss_onlisans", explanation: "Yüz, gül ve yol kelimelerinin birden fazla anlamı varken masa kelimesinin yoktur." },
  { id: "onl_tr_9", subject: "Türkçe", question: "Aşağıdaki cümlelerin hangisinde bir edat (ilgeç) kullanılmıştır?", options: ["Ali ve Ayşe geldi.", "Benim kadar çalışkan değil.", "Oysa ki çok sevmiştim.", "Ama sen de haklısın."], correctIndex: 1, difficulty: "medium", examType: "kpss_onlisans", explanation: "'Kadar' kelimesi cümlede edat olarak kullanılmıştır." },
  { id: "onl_tr_10", subject: "Türkçe", question: "'Tatlı dil yılanı deliğinden çıkarır.' atasözünün ana fikri nedir?", options: ["Yılanlar tatlıyı sever.", "Tatlı konuşan insanlar tehlikelidir.", "Güler yüzlü ve tatlı sözlü olmak en inatçı kişileri bile yumuşatır.", "İnsanlarla konuşurken dikkatli olunmalıdır."], correctIndex: 2, difficulty: "easy", examType: "kpss_onlisans", explanation: "Güzel ve tatlı konuşmanın insanların olumsuz tutumlarını bile olumluya çevirebileceği anlatılır." },
  
  // MATEMATİK (ÖNLİSANS - 15 questions)
  { id: "onl_mat_1", subject: "Matematik", question: "2x + 5 = 17 denkleminde x kaçtır?", options: ["4", "5", "6", "7"], correctIndex: 2, difficulty: "easy", examType: "kpss_onlisans", explanation: "2x = 17 - 5 => 2x = 12 => x = 6." },
  { id: "onl_mat_2", subject: "Matematik", question: "Bir karenin alanı 64 cm² ise çevresi kaç cm'dir?", options: ["24", "32", "40", "64"], correctIndex: 1, difficulty: "medium", examType: "kpss_onlisans", explanation: "Alanı 64 ise bir kenarı 8 cm'dir. Çevresi 4 * 8 = 32 cm'dir." },
  { id: "onl_mat_3", subject: "Matematik", question: "%40 karla 140 TL'ye satılan bir malın maliyet fiyatı nedir?", options: ["80", "90", "100", "110"], correctIndex: 2, difficulty: "medium", examType: "kpss_onlisans", explanation: "1.4 * Maliyet = 140 => Maliyet = 100 TL." },
  { id: "onl_mat_4", subject: "Matematik", question: "1/2, 1/3, 1/4 kesirlerinin toplamı kaçtır?", options: ["11/12", "9/12", "13/12", "15/12"], correctIndex: 2, difficulty: "medium", examType: "kpss_onlisans", explanation: "Paydaları 12'de eşitleriz: 6/12 + 4/12 + 3/12 = 13/12." },
  { id: "onl_mat_5", subject: "Matematik", question: "Hızı 80 km/sa olan bir araç 5 saatte kaç km yol alır?", options: ["350", "400", "450", "500"], correctIndex: 1, difficulty: "easy", examType: "kpss_onlisans", explanation: "Yol = Hız x Zaman => 80 x 5 = 400 km." },
  { id: "onl_mat_6", subject: "Matematik", question: "3 sayısının 4 katının 5 eksiği kaçtır?", options: ["5", "7", "9", "12"], correctIndex: 1, difficulty: "easy", examType: "kpss_onlisans", explanation: "3 x 4 = 12, 12 - 5 = 7." },
  { id: "onl_mat_7", subject: "Matematik", question: "İki sayının toplamı 20, farkı 6'dır. Büyük sayı kaçtır?", options: ["10", "12", "13", "14"], correctIndex: 2, difficulty: "medium", examType: "kpss_onlisans", explanation: "x+y=20, x-y=6. Taraf tarafa toplarsak 2x=26 => x=13." },
  { id: "onl_mat_8", subject: "Matematik", question: "1'den 100'e kadar (1 ve 100 dahil) kaç tane 9 rakamı kullanılır?", options: ["10", "19", "20", "21"], correctIndex: 2, difficulty: "hard", examType: "kpss_onlisans", explanation: "Birler basamağında 10 tane (9, 19...99), onlar basamağında 10 tane (90..99) toplam 20 tane." },
  { id: "onl_mat_9", subject: "Matematik", question: "Bir zar atıldığında üst yüze gelen sayının asal olma olasılığı nedir?", options: ["1/6", "1/3", "1/2", "2/3"], correctIndex: 2, difficulty: "medium", examType: "kpss_onlisans", explanation: "Asal sayılar 2, 3, 5'tir. Toplam 3 tane. 3/6 = 1/2." },
  { id: "onl_mat_10", subject: "Matematik", question: "2^3 x 2^4 işleminin sonucu nedir?", options: ["2^7", "4^7", "2^12", "4^12"], correctIndex: 0, difficulty: "easy", examType: "kpss_onlisans", explanation: "Üslü sayılarda çarpma işleminde tabanlar aynıysa üsler toplanır. 3+4=7 => 2^7." },
  
  // TARİH (ÖNLİSANS - 15 questions)
  { id: "onl_tar_1", subject: "Tarih", question: "Mustafa Kemal Paşa'nın 'Ordular, ilk hedefiniz Akdeniz'dir. İleri!' emrini verdiği savaş hangisidir?", options: ["Birinci İnönü", "Sakarya", "Büyük Taarruz", "Çanakkale"], correctIndex: 2, difficulty: "easy", examType: "kpss_onlisans", explanation: "Bu emir 1922 yılındaki Büyük Taarruz sırasında verilmiştir." },
  { id: "onl_tar_2", subject: "Tarih", question: "Mudanya Ateşkes Antlaşması hangi yıl imzalanmıştır?", options: ["1920", "1921", "1922", "1923"], correctIndex: 2, difficulty: "medium", examType: "kpss_onlisans", explanation: "Kurtuluş Savaşı'nın silahlı mücadelesini bitiren Mudanya Ateşkesi 11 Ekim 1922'de imzalanmıştır." },
  { id: "onl_tar_3", subject: "Tarih", question: "Aşağıdakilerden hangisi Atatürk'ün 'Milliyetçilik' ilkesi ile doğrudan ilgilidir?", options: ["Aşar vergisinin kaldırılması", "Türk Tarih Kurumunun kurulması", "Halifeliğin kaldırılması", "Soyadı Kanununun kabulü"], correctIndex: 1, difficulty: "medium", examType: "kpss_onlisans", explanation: "Türk Tarih ve Türk Dil Kurumlarının kurulması doğrudan milliyetçilik ilkesi ile ilgilidir." },
  { id: "onl_tar_4", subject: "Tarih", question: "TBMM'nin ilk başkanı kimdir?", options: ["İsmet İnönü", "Rauf Orbay", "Mustafa Kemal Atatürk", "Ali Fethi Okyar"], correctIndex: 2, difficulty: "easy", examType: "kpss_onlisans", explanation: "23 Nisan 1920'de açılan TBMM'nin ilk başkanı Mustafa Kemal Paşa'dır." },
  { id: "onl_tar_5", subject: "Tarih", question: "Osmanlı Devleti'nde padişahın yetkilerini ilk kez kısıtlayan belge hangisidir?", options: ["Tanzimat Fermanı", "Islahat Fermanı", "Kanun-i Esasi", "Sened-i İttifak"], correctIndex: 3, difficulty: "hard", examType: "kpss_onlisans", explanation: "1808 yılında II. Mahmut ile ayanlar arasında imzalanan Sened-i İttifak, padişahın yetkilerini kısıtlayan ilk belgedir." },
  { id: "onl_tar_6", subject: "Tarih", question: "Aşağıdakilerden hangisi Birinci Dünya Savaşı'nda Osmanlı Devleti'nin taarruz cephelerinden biridir?", options: ["Çanakkale", "Suriye-Filistin", "Kafkas", "Hicaz-Yemen"], correctIndex: 2, difficulty: "medium", examType: "kpss_onlisans", explanation: "Osmanlı Devleti'nin I. Dünya Savaşı'ndaki taarruz cepheleri Kafkas ve Kanal cepheleridir." },
  { id: "onl_tar_7", subject: "Tarih", question: "Misak-ı Milli kararları nerede kabul edilmiştir?", options: ["Amasya", "Erzurum", "Sivas", "Son Osmanlı Mebusan Meclisi"], correctIndex: 3, difficulty: "medium", examType: "kpss_onlisans", explanation: "Misak-ı Milli kararları 28 Ocak 1920'de İstanbul'da toplanan Son Osmanlı Mebusan Meclisi'nde kabul edilmiştir." },
  { id: "onl_tar_8", subject: "Tarih", question: "Saltanatın kaldırılması hangi tarihte gerçekleşmiştir?", options: ["1 Kasım 1922", "29 Ekim 1923", "3 Mart 1924", "23 Nisan 1920"], correctIndex: 0, difficulty: "medium", examType: "kpss_onlisans", explanation: "Saltanat 1 Kasım 1922'de TBMM tarafından kaldırılmıştır." },
  { id: "onl_tar_9", subject: "Tarih", question: "Tekalif-i Milliye emirleri hangi savaştan önce yayımlanmıştır?", options: ["Birinci İnönü", "İkinci İnönü", "Sakarya Meydan Muharebesi", "Büyük Taarruz"], correctIndex: 2, difficulty: "hard", examType: "kpss_onlisans", explanation: "Eskişehir-Kütahya Savaşlarından sonra, Sakarya Meydan Muharebesi'nden önce yayımlanmıştır." },
  { id: "onl_tar_10", subject: "Tarih", question: "Harf İnkılabı hangi yıl yapılmıştır?", options: ["1926", "1927", "1928", "1931"], correctIndex: 2, difficulty: "easy", examType: "kpss_onlisans", explanation: "Yeni Türk Harfleri 1 Kasım 1928'de kabul edilmiştir." },

  // COĞRAFYA (ÖNLİSANS - 10 questions)
  { id: "onl_cog_1", subject: "Coğrafya", question: "Türkiye'nin en kalabalık ili hangisidir?", options: ["Ankara", "İzmir", "Bursa", "İstanbul"], correctIndex: 3, difficulty: "easy", examType: "kpss_onlisans", explanation: "İstanbul, Türkiye'nin nüfus bakımından en büyük ilidir." },
  { id: "onl_cog_2", subject: "Coğrafya", question: "Türkiye'nin en uzun kara sınırı hangi ülke iledir?", options: ["Yunanistan", "Bulgaristan", "Suriye", "İran"], correctIndex: 2, difficulty: "medium", examType: "kpss_onlisans", explanation: "Türkiye'nin en uzun kara sınırı (911 km) Suriye iledir." },
  { id: "onl_cog_3", subject: "Coğrafya", question: "Karadeniz Bölgesi'nde en çok yetiştirilen tarım ürünü aşağıdakilerden hangisidir?", options: ["Pamuk", "Çay", "Buğday", "Zeytin"], correctIndex: 1, difficulty: "easy", examType: "kpss_onlisans", explanation: "Çay, Türkiye'de sadece Karadeniz Bölgesi'nde (Doğu Karadeniz) yetiştirilir." },
  { id: "onl_cog_4", subject: "Coğrafya", question: "Aşağıdakilerden hangisi Ege Bölgesi'ndeki kırıklı dağlardan biri değildir?", options: ["Madra", "Yunt", "Bozdağlar", "Kaçkar"], correctIndex: 3, difficulty: "medium", examType: "kpss_onlisans", explanation: "Kaçkar Dağları, Karadeniz Bölgesi'nde yer alan kıvrım dağlarıdır." },
  { id: "onl_cog_5", subject: "Coğrafya", question: "Türkiye'nin 'tahıl ambarı' olarak bilinen bölgesi hangisidir?", options: ["Marmara", "İç Anadolu", "Güneydoğu Anadolu", "Akdeniz"], correctIndex: 1, difficulty: "easy", examType: "kpss_onlisans", explanation: "İç Anadolu Bölgesi, geniş düzlükleri ve karasal iklimiyle buğday üretiminde ilk sıradadır." },
  { id: "onl_cog_6", subject: "Coğrafya", question: "Ergene Havzası hangi coğrafi bölgemizde yer alır?", options: ["Ege", "Marmara", "Akdeniz", "Karadeniz"], correctIndex: 1, difficulty: "medium", examType: "kpss_onlisans", explanation: "Ergene Havzası, Marmara Bölgesi'nin Trakya kesiminde yer alır." },
  { id: "onl_cog_7", subject: "Coğrafya", question: "Türkiye'de çeltik (pirinç) üretiminde ilk sırada yer alan il hangisidir?", options: ["Edirne", "Samsun", "Balıkesir", "Çorum"], correctIndex: 0, difficulty: "hard", examType: "kpss_onlisans", explanation: "Türkiye çeltik üretiminin yarısına yakını Edirne (Ergene Havzası) tarafından karşılanır." },
  { id: "onl_cog_8", subject: "Coğrafya", question: "Seyhan ve Ceyhan nehirlerinin oluşturduğu Türkiye'nin en büyük delta ovası hangisidir?", options: ["Çarşamba", "Bafra", "Çukurova", "Silifke"], correctIndex: 2, difficulty: "easy", examType: "kpss_onlisans", explanation: "Çukurova, Seyhan ve Ceyhan nehirlerinin taşıdığı alüvyonlarla oluşmuş en büyük delta ovamızdır." },

  // VATANDAŞLIK (ÖNLİSANS - 10 questions)
  { id: "onl_vat_1", subject: "Vatandaşlık", question: "Aşağıdakilerden hangisi temel hak ve hürriyetlerin özelliklerinden biri değildir?", options: ["Devredilemezler", "Vazgeçilemezler", "Sınırsızdırlar", "Dokunulmazdırlar"], correctIndex: 2, difficulty: "medium", examType: "kpss_onlisans", explanation: "Temel hak ve hürriyetler sınırsız değildir; anayasada belirtilen nedenlerle kanunla sınırlandırılabilirler." },
  { id: "onl_vat_2", subject: "Vatandaşlık", question: "Kanunları yayımlamak kimin görevidir?", options: ["TBMM Başkanı", "Cumhurbaşkanı", "Adalet Bakanı", "Anayasa Mahkemesi Başkanı"], correctIndex: 1, difficulty: "easy", examType: "kpss_onlisans", explanation: "TBMM tarafından kabul edilen kanunları 15 gün içinde yayımlamak veya geri göndermek Cumhurbaşkanının görevidir." },
  { id: "onl_vat_3", subject: "Vatandaşlık", question: "T.C. Anayasasına göre devletin şekli nedir?", options: ["Monarşi", "Teokrasi", "Oligarşi", "Cumhuriyet"], correctIndex: 3, difficulty: "easy", examType: "kpss_onlisans", explanation: "Anayasa Md. 1: Türkiye Devleti bir Cumhuriyettir." },
  { id: "onl_vat_4", subject: "Vatandaşlık", question: "Milletvekili seçilme yaşı kaçtır?", options: ["18", "21", "25", "30"], correctIndex: 0, difficulty: "easy", examType: "kpss_onlisans", explanation: "2017 anayasa değişikliği ile milletvekili seçilme yaşı 18'e indirilmiştir." },
  { id: "onl_vat_5", subject: "Vatandaşlık", question: "Yerel seçimler kaç yılda bir yapılır?", options: ["3", "4", "5", "7"], correctIndex: 2, difficulty: "medium", examType: "kpss_onlisans", explanation: "Anayasaya göre mahalli idareler seçimleri (yerel seçimler) 5 yılda bir yapılır." },
  { id: "onl_vat_6", subject: "Vatandaşlık", question: "Bir kimsenin suçluluğu mahkeme kararıyla saptanana kadar masum sayılması ilkesine ne ad verilir?", options: ["Kanunilik", "Eşitlik", "Masumiyet Karinesi", "Şahsilik"], correctIndex: 2, difficulty: "medium", examType: "kpss_onlisans", explanation: "Suçluluğu hükmen sabit oluncaya kadar kimse suçlu sayılamaz (Masumiyet Karinesi)." },

  // GÜNCEL BİLGİLER (ÖNLİSANS - 5 questions)
  { id: "onl_gun_1", subject: "Güncel Bilgiler", question: "2024 Yaz Olimpiyat Oyunları hangi şehirde düzenlenmiştir?", options: ["Tokyo", "Londra", "Paris", "Los Angeles"], correctIndex: 2, difficulty: "medium", examType: "kpss_onlisans", explanation: "2024 Yaz Olimpiyatları Paris'te (Fransa) düzenlenmiştir." },
  { id: "onl_gun_2", subject: "Güncel Bilgiler", question: "NATO'ya 2024 yılında katılan son ülke hangisidir?", options: ["Finlandiya", "İsveç", "Ukrayna", "Bosna Hersek"], correctIndex: 1, difficulty: "hard", examType: "kpss_onlisans", explanation: "İsveç, 2024 yılında NATO'nun 32. üyesi olmuştur." },
  { id: "onl_gun_3", subject: "Güncel Bilgiler", question: "Türkiye'nin ilk astronotu Alper Gezeravcı hangi uzay misyonu ile uzaya gitmiştir?", options: ["Axiom-3 (Ax-3)", "Apollo 11", "Artemis", "SpaceX Crew-5"], correctIndex: 0, difficulty: "medium", examType: "kpss_onlisans", explanation: "Alper Gezeravcı, Axiom Space'in Ax-3 misyonu kapsamında uzaya gitmiştir." },

  // HUKUK (LİSANS - 10 questions)
  { id: "lis_huk_1", subject: "Hukuk", question: "Bir hakkın kazanılmasında geçerli olan temel ilke hangisidir?", options: ["Dürüstlük Kuralı (Objektif İyiniyet)", "İyiniyet (Subjektif İyiniyet)", "Sözleşme Özgürlüğü", "Kusursuz Sorumluluk"], correctIndex: 1, difficulty: "hard", examType: "kpss_lisans", explanation: "Hakların KAZANILMASINDA iyiniyet (subjektif iyiniyet), KULLANILMASINDA ise dürüstlük kuralı (objektif iyiniyet) geçerlidir." },
  { id: "lis_huk_2", subject: "Hukuk", question: "Aşağıdakilerden hangisi medeni hukukun alt dallarından biri değildir?", options: ["Kişiler Hukuku", "Aile Hukuku", "Eşya Hukuku", "Ticaret Hukuku"], correctIndex: 3, difficulty: "medium", examType: "kpss_lisans", explanation: "Ticaret Hukuku ayrı bir özel hukuk dalıdır. Medeni hukukun alt dalları: Kişiler, Aile, Miras, Eşya." },
  { id: "lis_huk_3", subject: "Hukuk", question: "Suçun kanuni tanımındaki unsurların bilerek ve istenerek gerçekleştirilmesine ne ad verilir?", options: ["Kast", "Taksir", "Olası Kast", "Bilinçli Taksir"], correctIndex: 0, difficulty: "easy", examType: "kpss_lisans", explanation: "Kast, suçun kanuni tanımındaki unsurların bilerek ve istenerek gerçekleştirilmesidir." },

  // İKTİSAT (LİSANS - 10 questions)
  { id: "lis_ikt_1", subject: "İktisat", question: "Aşağıdakilerden hangisi makro iktisadın inceleme alanlarından biridir?", options: ["Firma teorisi", "Tüketici dengesi", "Enflasyon oranı", "Piyasa dengesi"], correctIndex: 2, difficulty: "easy", examType: "kpss_lisans", explanation: "Enflasyon, işsizlik, büyüme, milli gelir gibi konular makro iktisadın inceleme alanıdır." },
  { id: "lis_ikt_2", subject: "İktisat", question: "Tam rekabet piyasasında firmanın kısa dönemde kârını maksimize ettiği nokta hangisidir?", options: ["MR = MC", "P = AR", "TR = TC", "AR = AC"], correctIndex: 0, difficulty: "hard", examType: "kpss_lisans", explanation: "Tüm piyasalarda kâr maksimizasyon şartı Marjinal Gelir (MR) = Marjinal Maliyet (MC) eşitliğidir." },

  // MALİYE (LİSANS - 10 questions)
  { id: "lis_mal_1", subject: "Maliye", question: "Aşağıdakilerden hangisi kamu harcamalarının görünürde artış nedenlerinden biridir?", options: ["Nüfus artışı", "Enflasyon", "Devletin görevlerinin artması", "Savaşlar"], correctIndex: 1, difficulty: "hard", examType: "kpss_lisans", explanation: "Paranın satın alma gücünün düşmesi (enflasyon), kamu harcamalarının sadece görünürde (nominal) artmasına neden olur." }
];

const targetPath = path.join(__dirname, 'src', 'lib', 'data', 'duelQuestions.ts');
let content = fs.readFileSync(targetPath, 'utf8');

// We need to inject newQuestions before `\n];`
const closingBracketIndex = content.lastIndexOf('\n];');

if (closingBracketIndex === -1) {
    console.error("Could not find closing bracket");
    process.exit(1);
}

const before = content.slice(0, closingBracketIndex);
const after = content.slice(closingBracketIndex);

let appendString = "";
newQuestions.forEach(q => {
    appendString += `,\n  {\n    id: "${q.id}",\n    subject: "${q.subject}",\n    question: "${q.question}",\n    options: ${JSON.stringify(q.options)},\n    correctIndex: ${q.correctIndex},\n    difficulty: "${q.difficulty}",\n    examType: "${q.examType}",\n    explanation: "${q.explanation}"\n  }`;
});

const newContent = before + appendString + after;
fs.writeFileSync(targetPath, newContent, 'utf8');
console.log("Questions appended successfully!");
